[2024-06-18T16:31:41.486-0400] {processor.py:161} INFO - Started process (PID=20136) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:31:41.487-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:31:41.489-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:31:41.489-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:31:41.542-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:31:41.541-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:31:41.542-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:31:41.542-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:31:41.542-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:31:41.670-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2024-06-18T16:35:22.926-0400] {processor.py:161} INFO - Started process (PID=20348) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:35:22.931-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:35:22.932-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:35:22.932-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:35:22.972-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:35:22.971-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:35:22.972-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:35:22.972-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:35:22.973-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:35:23.089-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.170 seconds
[2024-06-18T16:38:47.621-0400] {processor.py:161} INFO - Started process (PID=20514) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:38:47.624-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:38:47.625-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:38:47.625-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:38:47.674-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:38:47.673-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:38:47.674-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:38:47.674-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:38:47.674-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:38:47.780-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.168 seconds
[2024-06-18T16:41:48.389-0400] {processor.py:161} INFO - Started process (PID=20841) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:41:48.391-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:41:48.392-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:41:48.391-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:41:48.430-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:41:48.429-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:41:48.431-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:41:48.430-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:41:48.431-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:41:48.516-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-06-18T16:44:49.683-0400] {processor.py:161} INFO - Started process (PID=21459) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:44:49.685-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:44:49.687-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:44:49.686-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:44:49.735-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:44:49.734-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:44:49.736-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:44:49.736-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:44:49.736-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:44:49.852-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.173 seconds
[2024-06-18T16:47:50.142-0400] {processor.py:161} INFO - Started process (PID=21627) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:47:50.146-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:47:50.147-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:47:50.147-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:47:50.199-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:47:50.199-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:47:50.200-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:47:50.200-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:47:50.200-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:47:50.326-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.188 seconds
[2024-06-18T16:51:00.157-0400] {processor.py:161} INFO - Started process (PID=21808) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:51:00.158-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:51:00.159-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:51:00.159-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:51:00.200-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:51:00.199-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:51:00.200-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:51:00.200-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:51:00.200-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:51:00.297-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.143 seconds
[2024-06-18T16:54:04.217-0400] {processor.py:161} INFO - Started process (PID=21958) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:54:04.219-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:54:04.221-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:54:04.221-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:54:04.268-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:54:04.268-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:54:04.269-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:54:04.269-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:54:04.269-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:54:04.400-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2024-06-18T16:57:13.578-0400] {processor.py:161} INFO - Started process (PID=22427) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:57:13.581-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T16:57:13.582-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:57:13.581-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:57:13.646-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:57:13.640-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T16:57:13.647-0400] {logging_mixin.py:188} INFO - [2024-06-18T16:57:13.647-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T16:57:13.647-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T16:57:13.801-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.239 seconds
[2024-06-18T17:00:39.764-0400] {processor.py:161} INFO - Started process (PID=22638) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:00:39.765-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:00:39.766-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:00:39.766-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:00:39.805-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:00:39.804-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:00:39.806-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:00:39.805-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:00:39.806-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:00:39.904-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.143 seconds
[2024-06-18T17:04:36.166-0400] {processor.py:161} INFO - Started process (PID=22882) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:04:36.167-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:04:36.168-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:04:36.168-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:04:36.218-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:04:36.216-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:04:36.219-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:04:36.219-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:04:36.219-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:04:36.353-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.190 seconds
[2024-06-18T17:08:17.516-0400] {processor.py:161} INFO - Started process (PID=23593) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:08:17.519-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:08:17.520-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:08:17.520-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:08:17.581-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:08:17.580-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:08:17.582-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:08:17.581-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:08:17.582-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:08:17.748-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.237 seconds
[2024-06-18T17:12:36.506-0400] {processor.py:161} INFO - Started process (PID=23958) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:12:36.508-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:12:36.510-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:12:36.509-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:12:36.572-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:12:36.571-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:12:36.573-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:12:36.572-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:12:36.573-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:12:36.740-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.239 seconds
[2024-06-18T17:18:05.276-0400] {processor.py:161} INFO - Started process (PID=24303) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:18:05.279-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:18:05.280-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:18:05.280-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:18:05.352-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:18:05.351-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:18:05.355-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:18:05.352-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:18:05.356-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:18:05.565-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.296 seconds
[2024-06-18T17:22:26.668-0400] {processor.py:161} INFO - Started process (PID=24631) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:22:26.669-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:22:26.670-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:22:26.669-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:22:26.725-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:22:26.724-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:22:26.725-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:22:26.725-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:22:26.726-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:22:26.872-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.209 seconds
[2024-06-18T17:26:56.613-0400] {processor.py:161} INFO - Started process (PID=24928) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:26:56.640-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:26:56.641-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:26:56.641-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:26:56.787-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:26:56.786-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:26:56.788-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:26:56.787-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:26:56.788-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:26:57.034-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.426 seconds
[2024-06-18T17:31:23.422-0400] {processor.py:161} INFO - Started process (PID=25243) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:31:23.425-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:31:23.426-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:31:23.426-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:31:23.493-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:31:23.492-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:31:23.494-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:31:23.494-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:31:23.494-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:31:23.664-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.247 seconds
[2024-06-18T17:36:42.665-0400] {processor.py:161} INFO - Started process (PID=25789) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:36:42.668-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:36:42.669-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:36:42.669-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:36:42.736-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:36:42.735-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:36:42.737-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:36:42.737-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:36:42.737-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:36:43.014-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.353 seconds
[2024-06-18T17:45:06.619-0400] {processor.py:161} INFO - Started process (PID=26621) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:45:06.621-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:45:06.622-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:45:06.622-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:45:06.672-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:45:06.671-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:45:06.673-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:45:06.673-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:45:06.674-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:45:06.822-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.206 seconds
[2024-06-18T17:49:26.674-0400] {processor.py:161} INFO - Started process (PID=27782) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:49:26.675-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:49:26.677-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:49:26.676-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:49:26.762-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:49:26.761-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:49:26.762-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:49:26.762-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:49:26.763-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:49:26.953-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.284 seconds
[2024-06-18T17:53:49.813-0400] {processor.py:161} INFO - Started process (PID=28600) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:53:49.816-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:53:49.817-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:53:49.816-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:53:49.933-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:53:49.928-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:53:49.935-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:53:49.934-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:53:49.936-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:53:50.202-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.393 seconds
[2024-06-18T17:57:25.449-0400] {processor.py:161} INFO - Started process (PID=29549) to work on /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:57:25.452-0400] {processor.py:830} INFO - Processing file /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T17:57:25.453-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:57:25.452-0400] {dagbag.py:545} INFO - Filling up the DagBag from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:57:25.529-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:57:25.528-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T17:57:25.529-0400] {logging_mixin.py:188} INFO - [2024-06-18T17:57:25.529-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T17:57:25.530-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T17:57:25.882-0400] {processor.py:183} INFO - Processing /Users/jbshome/Desktop/us_debt_etl_pipeline/debt_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.437 seconds
